#! /bin/bash
output=$(basename $1 ".ly")
echo "output "$output

cat $1 '/home/michael/All That Fall Lilypond Scores/quartet_score.ly' > /tmp/cat

lilypond -o "/home/michael/All That Fall Lilypond Scores/""$output"-Quartet /tmp/cat

