#! /bin/bash
output=$(basename $1 ".ly")
echo "output "$output

#cat $1 '/home/michael/myhack/Volumes/Zippy/puddle/All That Fall Lilypond Scores/vocalScore.ly' > /tmp/cat
cat $1 "$PWD"/vocalScore.ly > /tmp/cat

lilypond -o "$PWD"/"$output"-Vocal /tmp/cat

