#! /bin/bash

cat $1 '/home/michael/myhack/Volumes/Zippy/puddle/All That Fall Lilypond Scores/vocalScore.ly' > /tmp/cat

lilypond -o "/home/michael/myhack/Volumes/Zippy/puddle/All That Fall Lilypond Scores/CatTest.pdf" /tmp/cat

